[[constraint]]
name = "github.com/oneiro-ndev/metanode"
version = "~v1.1"

[[constraint]]
name = "github.com/oneiro-ndev/ndaumath"
version = "~v1.0"

[[override]]
name = "github.com/attic-labs/graphql"
branch = "master"

[[override]]
name = "github.com/tinylabs/msgp"
version = "v1.1.0"

[[override]]
name = "github.com/attic-labs/noms"
branch = "master"
source = "github.com/oneiro-ndev/noms"

[[override]]
name = "github.com/tendermint/tendermint"
version = "v0.30.1"

[[override]]
name = "github.com/gofrs/uuid"
version = "~v3.2"
